/**
 * Studio V2 shell: new components, design-system utilities, no bottom ranking tabs.
 * Original MetricCell / RelayPulseMatrix / MonitorTrendChart / ChannelStatusV2View stay untouched.
 */
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = resolve(__dirname, '../../..')

function read(rel: string) {
  return readFileSync(resolve(root, rel), 'utf8')
}

describe('channel-monitor-v2 studio structure', () => {
  it('route wrapper points V2 at the studio view without editing the original V2 page', () => {
    const wrapper = read('views/user/ChannelStatusView.vue')
    const original = read('views/user/ChannelStatusV2View.vue')
    expect(wrapper).toContain('ChannelStatusV2StudioView')
    expect(wrapper).not.toContain('ChannelStatusV2View v-else')
    expect(original).toContain('MetricCell')
    expect(original).toContain('RelayPulseMatrix')
    expect(original).toContain('MonitorTrendChart')
    expect(original).toContain("activeTab === 'models'")
  })

  it('studio page uses design-system chrome and omits models/errors/users tabs', () => {
    const src = read('views/user/ChannelStatusV2StudioView.vue')
    expect(src).toContain('page-header')
    expect(src).toContain('page-title')
    expect(src).toContain('class="card')
    expect(src).toContain('btn btn-secondary')
    expect(src).toContain('class="tab')
    expect(src).toContain('tab-active')
    expect(src).toContain('monitor-toolbar')
    expect(src).toContain('StudioKpiCard')
    expect(src).toContain('StudioStatusFaces')
    expect(src).toContain('StudioBrandIcon')
    expect(src).toContain(':row-index="card.rowIndex"')
    expect(src).toContain('v-for="section in pageSections"')
    expect(src).toContain('v-for="card in section.cards"')
    expect(src).toContain('studio-brand-section')
    expect(src).toContain('studio-brand-heading-mark')
    expect(src).toContain('studioBrandFill')
    expect(src).toContain('groupStudioCardsByBrand')
    expect(read('features/channel-monitor-v2-studio/studioFormat.ts')).toContain('sortStudioCardsByStatus')
    expect(src).toContain('pickStudioActiveGroups')
    expect(src).toContain('channelMonitorV2.studio.groups.active')
    expect(src).toContain('name="radar"')
    expect(src).toContain("kind: 'active'")
    expect(src).toContain('space-y-10')
    expect(src).toContain('<StudioBrandIcon v-else :platform="section.platform" size="sm" />')
    expect(src).toContain('studio-brand-heading-title')
    expect(src).toContain('text-sm font-extrabold')
    expect(src).toContain('size="xs"')
    expect(src).toContain('width: 1.25rem')
    expect(src).toContain('height: 1.25rem')
    expect(src).toContain('studio-card-grid')
    expect(src).not.toContain('v-studio-reflow')
    expect(src).not.toContain('vStudioReflow')
    expect(src).toContain('repeat(auto-fill, minmax(min(100%, 20rem), 1fr))')
    expect(src).not.toContain('max-width: 28rem')
    expect(src).not.toContain('max-width: 40rem')
    expect(src).not.toContain('h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-white ring-1')
    expect(src).toContain('studio-model-row')
    expect(src).toContain('flex-direction: column')
    expect(src).toContain('studio-model-card')
    expect(src).not.toContain('flex: 0 0 18rem')
    expect(src).toContain('rate-label')
    expect(src).toContain('useStudioGroupCards')
    expect(src).toContain('joined')
    expect(src).not.toContain('selectGroup')
    expect(src).not.toContain('studio-kpi--active')
    expect(src).not.toContain('selectedGroupKey')
    expect(src).not.toContain('withDemoBuckets')
    expect(src).not.toContain('rowHasActivity')
    expect(src).not.toContain('studioShowcaseRows')
    expect(src).toContain('channelMonitorV2.studio.groups.title')
    expect(src).toContain('channelMonitorV2.studio.brands.sectionAria')
    expect(src).not.toContain('channelMonitorV2.studio.faces.panHint')
    expect(src).not.toContain('channelMonitorV2.studio.faces.title')
    expect(src).not.toContain('channelMonitorV2.studio.faces.description')
    expect(src).not.toContain('channelMonitorV2.studio.faces.forModel')
    expect(src).toContain('useStudioGroupCards')
    expect(src).not.toContain('STUDIO_TEST_SLOT_INTERVAL_MS')
    expect(src).not.toContain('EMPTY_STUDIO_BUCKETS')
    expect(src).not.toContain('extendCoverage')
    expect(src).not.toContain('testSlotCount.value = 0')
    expect(src).not.toContain('syncTestSlots')
    expect(src).toContain('rgb(30 41 59)')
    expect(src).not.toContain('ACCENTS[index')
    expect(src).not.toContain("getMatrix(emptyFilter.value, 'platform_model'")
    expect(src).not.toContain('StudioPulseBoard')
    expect(src).not.toContain('StudioTrendArea')
    expect(src).not.toContain('StudioJourneyFlow')
    expect(src).not.toContain('StudioHealthRing')
    expect(src).not.toContain('FilterMultiSelect')
    expect(src).not.toContain('trendView')
    expect(src).not.toContain('healthModeOptions')
    expect(src).not.toContain('matrixGroupOptions')
    expect(src).not.toContain('MetricCell')
    expect(src).not.toContain('RelayPulseMatrix')
    expect(src).not.toContain('MonitorTrendChart')
    expect(src).not.toContain('MonitorRankBadge')
    expect(src).not.toContain('getModels')
    expect(src).not.toContain('getErrors')
    expect(src).not.toContain('getUsers')
    expect(src).not.toContain("activeTab === 'models'")
    expect(src).not.toContain("activeTab === 'errors'")
    expect(src).not.toContain('channelMonitorV2.tabs.models')
    expect(src).not.toContain('channelMonitorV2.tabs.errors')
    expect(src).not.toContain('channelMonitorV2.tabs.users')
    expect(src).not.toMatch(/min-width:\s*980px/)
    expect(src).not.toMatch(/min-w-\[980px\]/)
  })

  it('keeps active group cards off the user dashboard', () => {
    const home = read('views/user/DashboardView.vue')
    expect(home).not.toContain('UserDashboardActiveGroups')
    expect(home).toContain('UserDashboardRecentUsage')
    expect(home).toContain('UserDashboardQuickActions')
    expect(home).toContain('platformQuotas')
    expect(home).toContain('getMyPlatformQuotas')
    const cards = read('features/channel-monitor-v2-studio/useStudioGroupCards.ts')
    expect(cards).toContain("getMatrix(emptyFilter.value, 'platform_group'")
    expect(cards).toContain('mergeSelectedStudioGroups')
    expect(cards).toContain('snapshot.value?.config?.group_ids')
    expect(cards).toContain('userGroupsAPI')
    expect(cards).toContain('groupsAPI')
    expect(cards).toContain('formatStudioMultiplier')
    expect(cards).toContain('lookupStudioGroupRate')
    expect(cards).toContain('collectStudioGroupRates')
    expect(cards).toContain('formatStudioSuccessRate')
    expect(cards).toContain('channelMonitorV2.metrics.successRate')
    expect(cards).toContain('channelMonitorV2.metrics.ttft')
    expect(cards).toContain('channelMonitorV2.metrics.cacheRate')
    expect(cards).toContain('channelMonitorV2.studio.status.label')
    expect(cards).toContain('channelMonitorV2.studio.status.')
    expect(cards).toContain('overallToneFromRow')
    expect(cards).toContain('studioAccentFromState')
    expect(cards).toContain('errorRateTone')
    expect(cards).toContain('ttftTone')
    expect(cards).toContain('cacheTone')
  })

  it('studio KPI card uses stat-card utility', () => {
    const src = read('features/channel-monitor-v2-studio/StudioKpiCard.vue')
    expect(src).toContain('stat-card')
    expect(src).toContain('stat-label')
    expect(src).toContain('stat-value')
    expect(src).toContain('rounded-3xl')
    expect(src).toContain('StudioBrandIcon')
    expect(src).toContain('studio-kpi-brand')
    expect(src).toContain('studio-kpi-brand--ink')
    expect(src).toContain('studioBrandIsInk')
    expect(src).toContain('dark:invert')
    expect(src).toContain('studio-kpi-status')
    expect(src).toContain('ml-auto')
    expect(src).toContain('text-right')
    expect(src).toContain('studio-kpi-metrics')
    expect(src).toContain('minmax(0, 1fr)')
    expect(src).toContain('studio-kpi-rate')
    expect(src).toContain('flex: 0 0 auto')
    expect(src).toContain('studio-kpi-head')
    expect(src).toContain('studio-kpi-brand-row')
    expect(src).toContain('studio-kpi-name-row')
    expect(src).toContain('studio-kpi-name')
    expect(src).toContain('flex-wrap: nowrap')
    expect(src).toContain('studio-kpi--slate')
    expect(src).toContain('--studio-wash-from')
    expect(src).toContain('--studio-spark')
    expect(src).toContain('--studio-spark-fill')
    expect(src).toContain('studio-kpi--teal')
    expect(src).toContain('.dark .studio-kpi--joined')
    expect(src).toContain('in oklab')
    expect(src).not.toContain('rgb(255 251 235)')
    expect(src).not.toContain('rgb(69 47 12)')
    expect(src).not.toContain('#fb923c')
    expect(src).not.toContain('#ea580c')
    expect(src).not.toContain('truncateStudioGroupName')
    expect(src).not.toContain('displayLabel')
    expect(src).toContain('max-width: 66.666%')
    expect(src).toContain('text-overflow: ellipsis')
    expect(src).toContain('overflow: visible')
    expect(src).toContain('margin-top: 0.55rem')
    expect(src).toContain('StudioSparkChart')
    expect(src).toContain(':accent="accent"')
    expect(src).not.toContain('studio-kpi--active')
    expect(src).not.toContain('box-shadow: inset 0 0 0 2px')
    expect(src).toContain('--studio-faces-bg')
    expect(src).toContain('rgb(30 41 59)')
    expect(src).toContain('studio-kpi-metric-label')
    expect(src).toContain('.dark .studio-kpi-metric-label')
    expect(src).toContain('rgb(255 255 255)')
    expect(src).not.toContain('dark:!bg-dark-800')
    expect(src).not.toContain('background: transparent')
    expect(src).not.toContain('outline-offset')
    expect(src).toContain('transition: none')
  })

  it('status faces are a single-row cell grid with pulse tooltips', () => {
    const faces = read('features/channel-monitor-v2-studio/StudioStatusFaces.vue')
    const svg = read('features/channel-monitor-v2-studio/StudioFaceSvg.vue')
    expect(faces).toContain('--studio-face-min: 0.7rem')
    expect(faces).toContain('--studio-face-gap: 0.3rem')
    expect(faces).toContain('column-gap: var(--studio-face-gap)')
    expect(faces).toContain('--studio-face-cols')
    expect(faces).toContain('minmax(')
    expect(faces).toContain('1fr')
    expect(faces).not.toContain('minmax(0, 0.7rem)')
    expect(faces).toContain('aspect-ratio: 3 / 4')
    expect(faces).toContain('channelMonitorV2.studio.faces.recentCount')
    expect(faces).toContain('channelMonitorV2.studio.faces.past')
    expect(faces).toContain('channelMonitorV2.studio.faces.now')
    expect(faces).toContain('channelMonitorV2.bucket.minutes')
    expect(faces).not.toContain('max-width: 0.7rem')
    expect(faces).toContain('studio-face-cell')
    expect(faces).toContain('studioFacePalette')
    expect(faces).toContain('overallToneFromRow')
    expect(faces).toContain('studio-face-tooltip')
    expect(faces).toContain('bucketTooltipLines')
    expect(faces).toContain('studio-face--current')
    expect(faces).toContain('studio-face--enter')
    expect(faces).toContain('studio-face-pop')
    expect(faces).toContain('--studio-face-pop-ms: 0.5s')
    expect(faces).toContain('STUDIO_FACE_POP_MS')
    expect(faces).toContain('studio-faces-root')
    expect(faces).toContain('flex: 0 0 auto')
    expect(faces).toContain('is-hover')
    expect(faces).toContain('v-show="state.visible"')
    expect(faces).toContain("useStudioHoverTooltip('faces')")
    expect(faces).toContain('patch(faceLines(hovered))')
    expect(faces).toContain('v-if="isHost"')
    expect(faces).toContain('studio-face--hot')
    expect(faces).not.toContain('StudioFaceSvg')
    expect(faces).not.toContain('overflow-x-auto')
    expect(faces).not.toContain('studio-faces-scroller')
    expect(faces).not.toContain('studio-faces-nav')
    expect(faces).not.toContain('useShiftWheelPan')
    expect(faces).not.toContain('useDragInertiaPan')
    const spark = read('features/channel-monitor-v2-studio/StudioSparkChart.vue')
    expect(spark).toContain('studio-spark-dot--current')
    expect(spark).toContain('studio-spark-ping')
    expect(spark).toContain('studio-spark-dot--pending')
    expect(spark).toContain('studio-spark-dot--enter')
    expect(spark).toContain('border-radius: 50%')
    expect(spark).toContain('STUDIO_CHART_MIN_GAP')
    expect(spark).toContain('STUDIO_CHART_VISIBLE_DOTS')
    expect(spark).toContain('studioChartGap')
    expect(spark).toContain('studioAfterPaint')
    expect(spark).toContain('STUDIO_FACE_MOVE_MS')
    expect(spark).toContain('() => values.value.length, trackWidth')
    expect(spark).toContain('if (nextCount <= prevCount) return')
    expect(spark).toContain('is-page-hidden')
    expect(spark).toContain('animation: none')
    expect(spark).toContain('right: 0')
    expect(spark).toContain('v-show="state.visible"')
    expect(spark).toContain('patch(dotLines(hovered))')
    expect(spark).toContain('mask-image')
    expect(spark).toContain('fadeId')
    expect(spark).toContain('studio-spark-fill-top')
    expect(spark).toContain('allocStudioSparkIds')
    expect(spark).toContain('studioSparkPaint')
    expect(spark).toContain('visibleLeft')
    expect(spark).not.toContain('clip-path: inset')
    expect(spark).toContain('align-items: center')
    expect(spark).toContain('justify-content: center')
    expect(spark).not.toContain('margin: 5px auto 0')
    expect(faces).toContain('transparent')
    expect(faces).not.toContain('emoji')
    expect(faces).not.toContain('channelMonitorV2.studio.faces.title')
    expect(faces).not.toContain('class="card')
    expect(svg).toContain('<svg')
    expect(svg).toContain('viewBox="0 0 64 64"')
    expect(svg).toContain('studioFacePalette')
    expect(svg).not.toContain('radialGradient')
    const format = read('features/channel-monitor-v2-studio/studioFormat.ts')
    expect(format).not.toContain('truncateStudioGroupName')
    expect(format).not.toContain('STUDIO_GROUP_NAME_WIDTH')
    expect(format).toContain('mergeSelectedStudioGroups')
    expect(format).toContain('emptyStudioMetrics')
    expect(format).toContain("['openai', 'anthropic', 'grok']")
    expect(format).toContain('formatStudioSuccessRate')
    expect(format).toContain('formatStudioErrorRate')
    expect(format).toContain('studioAccentFromState')
    expect(format).toContain('studioSparkPaint')
    expect(format).toContain('allocStudioSparkIds')
    expect(format).toContain('pickStudioActiveGroups')
    expect(format).not.toContain('pickDashboardActiveGroups')
    expect(format).toContain('STUDIO_ACTIVE_GROUP_LIMIT = 4')
    expect(format).toContain('#6EE7B7')
    expect(format).toContain('#FDBA74')
    expect(format).toContain('#FCA5A5')
    expect(format).toContain('#E5E7EB')
    expect(format).toContain('studioFacePalette')
    const buckets = read('features/channel-monitor-v2-studio/studioBuckets.ts')
    expect(buckets).toContain('STUDIO_MAX_SLOTS = 18')
    expect(buckets).toContain('limitStudioStarts')
    expect(buckets).toContain('studioNativeSlotCount')
    expect(buckets).toContain('studioSlotCap')
    expect(buckets).toContain('isStudioBucketEmpty')
    expect(buckets).toContain('studioSparkValue')
    expect(spark).toContain('studioSparkValue')
    expect(buckets).toContain('exclusiveEndFromNow')
    expect(faces).toContain('isStudioBucketEmpty')
    expect(spark).toContain('isStudioBucketEmpty')
    const demo = read('features/channel-monitor-v2-studio/studioDemo.ts')
    expect(demo).toContain('STUDIO_TEST_SLOT_INTERVAL_MS = 10_000')
    expect(demo).toContain('STUDIO_FACE_POP_MS = 500')
    expect(demo).toContain('STUDIO_FACE_MOVE_MS = 500')
    expect(demo).toContain('STUDIO_FACE_STAGGER_MS = 120')
    expect(demo).toContain('STUDIO_CHART_MIN_GAP = 40')
    expect(demo).toContain('STUDIO_CHART_VISIBLE_DOTS = 5')
    expect(demo).toContain('isLiveBucket')
    expect(demo).toContain('demoOrigins')
    expect(demo).toContain('demoTimelineIndex')
    expect(demo).toContain('rate: 0.08')
    expect(svg).not.toMatch(/[\u{1F600}-\u{1F64F}]/u)
  })
})
